### ISSUE TITLE
Auto-redirect to homepage

### ISSUE THREAD

**Issue by guim31** [isc30/eMulerr#2]
OS : Unraid
Using docker compose : 
```
services:
  emulerr:
    image: isc30/emulerr:latest
    container_name: emulerr
    restart: unless-stopped
    tty: true
    environment:
      - PUID=99
      - PGID=100
    ports:
      - "3003:3000" # web ui
      - "4662:4662" # ed2k tcp
      - "4662:4662/udp" # ed2k udp
      - "4665:4665/udp" # ed2k global search udp (tcp port +3)
    volumes:
      - /mnt/user/appdata/emulerr:/config
      - /mnt/user/downloads/nzb_torrents_completed:/downloads
```

After few minutes of working I'm unable to reach /download_client or / search page. I'm redirected to the homepage.

Here are the logs : 

```
file:///emulerr/build/server/index.js:1182
    ...downloads.sort(
                 ^

TypeError: Cannot assign to read only property '0' of object '[object Array]'
    at Array.sort (<anonymous>)
    at file:///emulerr/build/server/index.js:1182:18
    at async file:///emulerr/build/server/index.js:144:32

Node.js v20.15.1

> start
> cross-env NODE_ENV=production node ./server.js

[setLogLevel] Setting log level to "info"
[18:10:42][info] [initializeJobs] Initializing jobs...
[18:10:42][info] Express server listening at http://localhost:3000
[18:10:46][error] TypeError: Cannot assign to read only property '0' of object '[object Array]'
[18:10:48][error] TypeError: Cannot assign to read only property '0' of object '[object Array]'
[18:10:49][error] TypeError: Cannot assign to read only property '0' of object '[object Array]'
[18:10:56][error] TypeError: Cannot assign to read only property '0' of object '[object Array]'
[18:11:01][error] TypeError: Cannot assign to read only property '0' of object '[object Array]'
[18:11:05][error] TypeError: Cannot assign to read only property '0' of object '[object Array]'
[18:11:12][error] TypeError: Cannot assign to read only property '0' of object '[object Array]'
[18:11:13][error] TypeError: Cannot assign to read only property '0' of object '[object Array]'
[18:11:21][error] TypeError: Cannot assign to read only property '0' of object '[object Array]'
[18:11:22][error] TypeError: Cannot assign to read only property '0' of object '[object Array]'
[18:11:23][error] TypeError: Cannot assign to read only property '0' of object '[object Array]'
[18:11:23][error] TypeError: Cannot assign to read only property '0' of object '[object Array]'
[18:11:24][error] TypeError: Cannot assign to read only property '0' of object '[object Array]'
[18:11:25][error] TypeError: Cannot assign to read only property '0' of object '[object Array]'
[18:11:25][error] TypeError: Cannot assign to read only property '0' of object '[object Array]'
[18:11:26][error] TypeError: Cannot assign to read only property '0' of object '[object Array]'
[18:11:26][error] TypeError: Cannot assign to read only property '0' of object '[object Array]'
[18:11:27][error] TypeError: Cannot assign to read only property '0' of object '[object Array]'
[18:11:31][error] TypeError: Cannot assign to read only property '0' of object '[object Array]'
[18:13:12][error] TypeError: Cannot assign to read only property '0' of object '[object Array]'
[18:13:13][error] TypeError: Cannot assign to read only property '0' of object '[object Array]'
crond[48]: USER root pid 904 cmd run-parts /etc/periodic/15min
```

**Comment by isc30** [comment]
Issue fixed in latest version
